INSERT INTO developers(developer_name) VALUES('Nintendo');
INSERT INTO developers(developer_name) VALUES('Valve Corp');
INSERT INTO developers(developer_name) VALUES('Rockstar Games');
INSERT INTO developers(developer_name) VALUES('Electronic Arts');
INSERT INTO developers(developer_name) VALUES('Activision');
INSERT INTO developers(developer_name) VALUES('Ubisoft');
INSERT INTO developers(developer_name) VALUES('BioWare');
INSERT INTO developers(developer_name) VALUES('Naughty Dog');
INSERT INTO developers(developer_name) VALUES('Square Enix');
INSERT INTO developers(developer_name) VALUES('Bungie');
INSERT INTO developers(developer_name) VALUES('Mojang');
INSERT INTO developers(developer_name) VALUES('Epic Games');
INSERT INTO developers(developer_name) VALUES('Blizzard');
INSERT INTO developers(developer_name) VALUES('Bethesda');
INSERT INTO developers(developer_name) VALUES('Coffee Stain Studios');

INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Super Mario Bros', 19.99, 40240000, 1);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('The Legend of Zelda: Ocarina of Time', 9.99, 7600000, 1);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Portal 2', 19.99, 4000000, 2);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Half Life 2', 9.99, 6500000, 2);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Grand Theft Auto V', 19.99, 160000000, 3);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Red Dead Redemption 2', 29.99, 43000000, 3);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Apex Legends', 0.00, 140000000, 4);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Battlefield 1', 19.99, 15000000, 4);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Call of Duty: Warzone', 0.00, 50000000, 5);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Call of Duty: Black Ops', 39.99, 30720000, 5);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Tom Clancy''s Rainbow Six Siege', 19.99, 10000000, 6);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Assassin''s Creed: Odyssey', 59.99, 10000000, 6);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Mass Effect 3', 19.99, 3500000, 7);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Baldur''s Gate', 4.99, 1000000, 7);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Uncharted 2: Among Thieves', 29.99, 20000000, 8);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('The Last of Us', 9.99, 10000000, 8);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Final Fantasy VII', 14.99, 14000000, 9);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Tomb Raider', 19.99, 11000000, 9);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Halo: Combat Evolved', 9.99, 60000000, 10);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Destiny 2', 29.99, 15000000, 10);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Minecraft', 24.99, 240000000, 11);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Cobalt', 14.99, 20000, 11);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Fortnite', 0.00, 400000000, 12);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Dauntless', 9.99, 10000000, 12);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Overwatch', 39.99, 50000000, 13);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('World of Warcraft', 14.99, 14000000, 13);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('The Elder Scrolls V: Skyrim', 39.99, 35000000, 14);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('DOOM Eternal', 29.99, 8000000, 14);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Deep Rock Galactic', 24.99, 3500000, 15);
INSERT INTO games(game_name, price, copies_sold, developer_id) VALUES('Valheim', 19.99, 9000000, 15);

INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('dhoward', 'Dwayne', 'Howard', 56, 'United States of America', 100.00);
INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('barnlaugsson', 'Bergsveinn', 'Arnlaugsson', 36, 'Iceland', 100.00);
INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('aeisenberg', 'Angelika', 'Eisenberg', 21, 'Germany', 100.00);
INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('jnygard', 'Joanna', 'Nygard', 41, 'Germany', 100.00);
INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('lfarber', 'Lisa', 'Farber', 23, 'Austria', 100.00);
INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('lcabrera', 'Loris', 'Cabrera', 37, 'Mexico', 100.00);
INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('nrodriguez', 'Nicolas', 'Rodriguez', 31, 'Brazil', 100.00);
INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('myudina', 'Marya', 'Yudina', 29, 'Russia', 100.00);
INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('cdouffet', 'Christelle', 'Douffet', 44, 'France', 100.00);
INSERT INTO users(profile_name, first_name, last_name, age, country, wallet) VALUES ('scarpenter', 'Sofia', 'Carpenter', 17, 'United Kingdom', 100.00);

INSERT INTO user_games (user_id, game_id) VALUES (1, 1);
INSERT INTO user_games (user_id, game_id) VALUES (1, 2);
INSERT INTO user_games (user_id, game_id) VALUES (1, 3);
INSERT INTO user_games (user_id, game_id) VALUES (1, 4);
INSERT INTO user_games (user_id, game_id) VALUES (2, 1);
INSERT INTO user_games (user_id, game_id) VALUES (2, 2);
INSERT INTO user_games (user_id, game_id) VALUES (2, 3);
INSERT INTO user_games (user_id, game_id) VALUES (2, 4);
INSERT INTO user_games (user_id, game_id) VALUES (3, 5);
INSERT INTO user_games (user_id, game_id) VALUES (3, 6);
INSERT INTO user_games (user_id, game_id) VALUES (3, 7);
INSERT INTO user_games (user_id, game_id) VALUES (3, 8);
INSERT INTO user_games (user_id, game_id) VALUES (4, 5);
INSERT INTO user_games (user_id, game_id) VALUES (4, 6);
INSERT INTO user_games (user_id, game_id) VALUES (4, 7);
INSERT INTO user_games (user_id, game_id) VALUES (4, 8);
INSERT INTO user_games (user_id, game_id) VALUES (5, 9);
INSERT INTO user_games (user_id, game_id) VALUES (5, 10);
INSERT INTO user_games (user_id, game_id) VALUES (6, 9);
INSERT INTO user_games (user_id, game_id) VALUES (6, 10);
INSERT INTO user_games (user_id, game_id) VALUES (7, 11);
INSERT INTO user_games (user_id, game_id) VALUES (7, 12);
INSERT INTO user_games (user_id, game_id) VALUES (8, 11);
INSERT INTO user_games (user_id, game_id) VALUES (8, 12);
INSERT INTO user_games (user_id, game_id) VALUES (9, 13);
INSERT INTO user_games (user_id, game_id) VALUES (9, 14);
INSERT INTO user_games (user_id, game_id) VALUES (9, 15);
INSERT INTO user_games (user_id, game_id) VALUES (9, 16);
INSERT INTO user_games (user_id, game_id) VALUES (10, 13);
INSERT INTO user_games (user_id, game_id) VALUES (10, 14);
INSERT INTO user_games (user_id, game_id) VALUES (10, 15);
INSERT INTO user_games (user_id, game_id) VALUES (10, 16);